### ISSUE TITLE
Add str.count

### ISSUE THREAD

**Issue by xhochy** [xhochy/fletcher#127]
- ✔️ [pandas function](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.count.html#pandas.Series.str.count)
- ✔️ [Python function](https://docs.python.org/3/library/stdtypes.html#str.count)
- ❌ C++ STL function
- ❌ needs a regular expression library
- ✔️ no need for a Unicode database for capitalization
- ✔️ can pre-compute output size as return value is a numeric array

Pseudo-Code:

```
Inputs: pat

output = IntArray(len(rows))
for i, row in enumerate(rows):
    count = 0
    for offset in range(len(row)):
        if pat == row[offset:len(pat)]:
        count += 1
    output[i] = count
```

**Comment by Alaxe** [comment]
The provided pseudo-code has produces a different result than the pandas count function when there are overlapping matches. Consider
```
>>> s = pd.Series(['aaaaaa'])
>>> s.str.count('aaa')
0    2
dtype: int64
```
The pseudocode above would instead find `4` matches. A more accurate version would be something like
```
for i, row in enumerate(rows):
    count = 0
    offset = 0
    while offset + len(pat) <= len(row):
        if pat == row[offset : offset + len(pat)]:
            count += 1
            offset += len(pat)
        else:
            offset += 1
    output[i] = count
```

In #164 we have an implementation of `count` that produces the same result as the pandas equivalent.

**Comment by xhochy** [comment]
Nice finding, I did ask myself this while reviewing your code. Can you comment in your implementation that this is done in such a way to match Python's behaviour?

**Comment by Alaxe** [comment]
Add an explanation as a comment in [fletcher/algorithms/strings.py][1].

[1]: https://github.com/Alaxe/fletcher/blob/dcab22d2642d482c7e6dfa435cf2a77b12152878/fletcher/algorithms/string.py#L198
