### ISSUE TITLE
Example in docs uses outdated FletcherArray

### ISSUE THREAD

**Issue by mrocklin** [xhochy/fletcher#150]
The getting started example (which is wonderfully simple by the way) uses FletcherArray, which seems to have been replaced by `FletcherContinuousArray` or `FletcherChunkedArray`

```python
import fletcher as fr
import pandas as pd

df = pd.DataFrame({
    'str_column': fr.FletcherArray(['Test', None, 'Strings'])
})
df.info()
```

**Comment by xhochy** [comment]
The `readthedocs` build was also broken, the updated version is now live at https://fletcher.readthedocs.io/en/latest/
