### ISSUE TITLE
`|=` and `&=` fail

### ISSUE THREAD

**Issue by lbittarello** [xhochy/fletcher#213]
Allegedly, because Fletcher doesn't support universal functions with keyword arguments.

MWE:

```python
import fletcher as fr
import numpy as np

x = fr.FletcherContinuousArray([0])
y = np.array([False])

y |= x == 1
```

This error came to fore because it breaks `replace` (e.g., `pd.Series(x).replace(0, 1)`).

**Comment by xhochy** [comment]
This sets `kwargs = {'out': (array([False]),)}`. I don't think we can actually support this as the fletcher array support nullability whereas the `numpy.ndarray` doesn't.
