### ISSUE TITLE
Feature request: Automatically infer Fletcher dtype to an existing DataFrame

### ISSUE THREAD

**Issue by caniko** [xhochy/fletcher#220]
A function that automatically infers Fletcher `dtype` to an existing `DataFrame`. This function would subsume `pandas.DataFrame.convert_dtypes`, [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.convert_dtypes.html).

Would it be correct that Fletcher `dtype` should be applied to every `object` `dtype`?

**Comment by xhochy** [comment]
This project has been archived as development has ceased around 2021.
With the support of [Apache Arrow-backed extension arrays in `pandas`](https://github.com/pandas-dev/pandas/pull/35259), the major goal of this project has been fulfilled.
