### ISSUE TITLE
Native implementation of ExtensionArray.unique

### ISSUE THREAD

**Issue by xhochy** [xhochy/fletcher#25]
Currently we use the default implementation https://github.com/pandas-dev/pandas/blob/2cbdd9a2cd19501c98582490e35c5402ae6de941/pandas/core/arrays/base.py#L382 that simply converts to object, runs Pandas' `unique` and then recreates a new ExtensionArray instance.

This depends on the Arrow upstream issue https://issues.apache.org/jira/browse/ARROW-2663

**Comment by birdsarah** [comment]
Just noting, that I think the upstream issue is complete.
