### ISSUE TITLE
How to use benchmarks.py?

### ISSUE THREAD

**Issue by woj-i** [xhochy/fletcher#63]
It's not clear how to use benchmarks py. IMO it would be nice to have the main nethod in that file, that is able to run benchmarks and print results.

**Comment by fjetter** [comment]
We're using [airspeed velocity](https://asv.readthedocs.io/en/stable/) to run the benchmarks. If you don't want to use the HTML reports you can run something like `asv run --python=same --show-stderr` which runs the benchmarks using the currently active interpreter and prints all results to the terminal.
